### ISSUE TITLE
FlexASIOGUI.exe refuses to launch after updating Visual Studio 2019 to version 16.9.0/16.9.1

### ISSUE THREAD

**Issue by borgeindergaard** [flipswitchingmonkey/FlexASIO_GUI#13]
FlexASIOGUI has been working fine for me for many months, and no hardware has changed on my end.
I recently updated Visual Studio 2019 Community to version 16.9.0/16.9.1 (the latest official VS2019 releases), and after that the FlexASUIGUI application refuses to start. It just goes all silent after trying to start it. No error messages, no GUI, nothing. But I do get these error messages in the Windows Event Log (Application log). I get these errors in the event log each time I try to start the application:

**ERROR - .NET Runtime - Event ID: 1026:**
Application: FlexASIOGUI.exe
CoreCLR Version: 4.700.21.6504
.NET Core Version: 3.1.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'SelectedIndex'. (Parameter 'value')
Actual value was 0.
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at FlexASIOGUI.Form1..ctor() in d:\Dev\FlexASIO_GUI\Form1.cs:line 71
   at FlexASIOGUI.Program.Main() in d:\Dev\FlexASIO_GUI\Program.cs:line 20

**ERROR - Application Error - Event ID: 1000:**
Faulting application name: FlexASIOGUI.exe, version: 1.0.0.0, time stamp: 0x5f1757ad
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0x0e9c5eae
Exception code: 0xe0434352
Fault offset: 0x000000000002d759
Faulting process id: 0x44fc
Faulting application start time: 0x01d7150e16ad9dd2
Faulting application path: C:\Program Files\FlexASIOGUI\FlexASIOGUI.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5b385b31-ebbb-42e6-8204-6c0b607989c1
Faulting package full name: 
Faulting package-relative application ID:

**Comment by DOCaCola** [comment]
Same issue here on a computer with just the latest core runtime installed. No Visual Studio installed.

Application: FlexASIOGUI.exe
CoreCLR Version: 4.700.21.11102
.NET Core Version: 3.1.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: InvalidArgument=Value mit dem Wert 0 ist für SelectedIndex ungültig. (Parameter 'value')
Actual value was 0.
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at FlexASIOGUI.Form1..ctor() in d:\Dev\FlexASIO_GUI\Form1.cs:line 71
   at FlexASIOGUI.Program.Main() in d:\Dev\FlexASIO_GUI\Program.cs:line 20

**Comment by flipswitchingmonkey** [comment]
I just published version 0.3, can you please try again?

**Comment by flipswitchingmonkey** [comment]
Closing under the assumption that it's sorted.
